name = "doodle"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glisten = ">= 8.0.3 and < 9.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
